add useRef
the-collab-lab/tcl-30-whats-near-me pull request #21
Opened 2021-08-12 02:41 UTC by jssckbl

## Description

We merged the branch `jw-ac-fix-drag-map` with `main`, when we should have first attempted to merge `main` into the branch `jw-ac-fix-drag-map`. 

This would have potentially helped work through any expected conflicts, without adversely affecting production in the process.

This pull request is bringing the code back to it's intended state for `jw-ac-fix-drag-map`. 
Once this PR approved, we will merge `main` INTO `jw-ac-fix-drag-map`, and then solve any resulting conflicts. 
Once the conflicts are solved, we will be able to merge `jw-ac-fix-drag-map` into `main`

## Related Issue

Reference [TCL30-18](https://github.com/the-collab-lab/tcl-30-whats-near-me/pull/18/files).

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
|    | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |
|   ✓  | :repeat: Same code, New PR     |

## Updates

### Before

See Reference [TCL30-18](https://github.com/the-collab-lab/tcl-30-whats-near-me/pull/18).

### After

See Reference [TCL30-18](https://github.com/the-collab-lab/tcl-30-whats-near-me/pull/18).

## Testing Steps / QA Criteria

See Reference [TCL30-18](https://github.com/the-collab-lab/tcl-30-whats-near-me/pull/18).

2021-08-12 12:04 UTC, laurenmbeatty requested changes

2021-08-12 12:04 UTC, laurenmbeatty commented on src/components/ShareMyLocationButton.js
> -  const handleStopSharing = () => {
We're still going to need this `handleStopSharing` function.

2021-08-12 12:04 UTC, laurenmbeatty commented on src/components/ShareMyLocationButton.js
> -    <button
We'll also need to preserve these changes, including the `buttonText`. Once the user shares their location, the button text should change to "Stop Sharing Location", and the `onClick` function to change to `handleStopSharing`.

2021-08-14 00:20 UTC, alxmcr commented on src/components/ShareMyLocationButton.js
> +  const buttonText = userLocationShared
Lauren : We added `buttonText` 😄  .

2021-08-14 00:20 UTC, alxmcr commented on src/components/ShareMyLocationButton.js
> +    <button
Lauren: We added their button 😄 .

2021-08-14 00:28 UTC, alxmcr commented
I'm so sorry for the inconvenience.

**Extra Comments:**
- We brought Katia & Megan's work to our branch (the last version) and added ours changes.
- We fixed the bug when we drag the map and change the map center location.
- I added two specific changes (after our previous PR): first,  remove the props for this component, because Katia & Megan thought a better idea, and second, there was an issue when you share, stop and try sharing your location again (it wasn't possible), inside `handleStopSharing` function we update `sharingLocation`'s value. It's fixed. (cc @jssckbl)

2021-08-14 00:29 UTC, laurenmbeatty approved these changes
yay!!!!!!! This is working beautifully now! Just tried it out on my phone. Let's get this merged! :shipit:

2021-08-14 00:31 UTC, merged